services:
  - type: web
    name: hariyali-app
    runtime: docker
    repo: https://github.com/Jashwanth2626/SUSTAINABLE-FERTILISER-USAGE-OPTIMISER-FOR-HIGHER-YIELD.git
    plan: starter
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
    autoDeploy: true

